version: '3.7'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: # your Database password
      POSTGRES_USER: # your Database user
      POSTGRES_DB: # your Database name
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:5433"
  bot:
    build: .
    command: sh -c "alembic upgrade head && python bot/__main__.py"
    restart: unless-stopped
    env_file:
      - ./.env # rename .env.example -> .env 
    depends_on: 
      - db

volumes:
  pgdata: