version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env  # Используем переменные из файла .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  postgres_data: {}